 function foo(){

   var title = ['vikram', 'red', 'kanchana'];

   for (i=0;i<title.length;i++){

   console.log (title[i].charAt(0).toUpperCase() + title[i].substring(1));

   }


}

foo();

var a = function () {

   var title = ['dikram', 'red', 'kanchana'];

   for (i=0;i<title.length;i++){
   
       console.log (title[i].charAt(0).toUpperCase() + title[i].substring(1));

}
}

();


(function () {

   var title = ['sikram', 'red', 'kanchana'];

    for (i=0;i<title.length;i++){
   
        console.log (title[i].charAt(0).toUpperCase() + title[i].substring(1));

    }
})

();

var a =  ()=>{
   var title = ['nikram', 'red', 'kanchana'];

     for (i=0;i<title.length;i++){
      
            console.log (title[i].charAt(0).toUpperCase() + title[i].substring(1));

     }
}

a();